<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>14.0</LangVersion>
		<Nullable>enable</Nullable>
		<RootNamespace>DeviceCore</RootNamespace>
		<Authors>nventive</Authors>
		<Company>nventive</Company>
		<AssemblyName>DeviceCore.Fakes</AssemblyName>
		<PackageId>DeviceCore.Fakes</PackageId>
		<Description>Fakes and mock implementations for DeviceCore.Abstractions, intended for use in unit testing and development scenarios.</Description>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/nventive/DeviceCore</PackageProjectUrl>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageTags>review;maui;winui;ios;android</PackageTags>
		<Copyright>https://github.com/nventive/DeviceCore/blob/main/LICENSE</Copyright>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/nventive/DeviceCore</RepositoryUrl>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

	<!-- This is to include the README.md file in the NuGet package. -->
	<ItemGroup>
		<None Include="..\..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
		<PackageReference Include="System.Reactive" Version="6.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DeviceCore.Abstractions\DeviceCore.Abstractions.csproj" />
	</ItemGroup>
</Project>
